import { TrendingNiche } from '../types/niches';

export const TRENDING_NICHES: TrendingNiche[] = [
  {
    id: 'apiculture',
    keyword: 'carnet de bord apiculture',
    title: 'Carnet Apiculteur',
    subtitle: 'Carnet de bord apiculture',
    emoji: '🍯',
    category: 'Animaux & Nature',
    difficulty: 'Facile',
    volumeScore: 62,
    volumeLevel: 'Moyen',
    opportunityScore: 'A+',
    trend: 'hot',
    description: 'Quasi aucun concurrent sérieux. Les apiculteurs amateurs cherchent des carnets de suivi de ruche structurés.',
    tags: ['ruche', 'abeilles', 'miel', 'apiculture'],
    monthlySearches: '~1 200',
  },
  {
    id: 'glycemie',
    keyword: 'journal de glycémie',
    title: 'Journal Glycémie',
    subtitle: 'Carnet de suivi diabète',
    emoji: '🩺',
    category: 'Santé',
    difficulty: 'Facile',
    volumeScore: 71,
    volumeLevel: 'Haut',
    opportunityScore: 'A+',
    trend: 'up',
    description: 'Forte demande des diabétiques de type 2. Recherches en croissance constante, peu de livres KDP de qualité.',
    tags: ['diabète', 'glycémie', 'santé', 'carnet suivi'],
    monthlySearches: '~3 400',
  },
  {
    id: 'coloriage-inverse',
    keyword: 'coloriage inversé adultes',
    title: 'Coloriage Inversé',
    subtitle: 'Sur fond noir — adultes',
    emoji: '🎨',
    category: 'Créativité',
    difficulty: 'Moyen',
    volumeScore: 78,
    volumeLevel: 'Haut',
    opportunityScore: 'B+',
    trend: 'hot',
    description: 'Tendance virale sur Pinterest. Les coloriages sur fond noir se vendent 2× plus cher que les classiques.',
    tags: ['coloriage noir', 'adultes', 'détente', 'art-thérapie'],
    monthlySearches: '~8 700',
  },
  {
    id: 'pilote',
    keyword: 'carnet de bord pilote',
    title: 'Carnet Pilote',
    subtitle: 'Logbook aviation',
    emoji: '✈️',
    category: 'Aviation',
    difficulty: 'Facile',
    volumeScore: 55,
    volumeLevel: 'Moyen',
    opportunityScore: 'A',
    trend: 'stable',
    description: 'Niche evergreen. Élèves pilotes et PPL cherchent des logbooks structurés et peu onéreux.',
    tags: ['aviation', 'pilote', 'logbook', 'ULM'],
    monthlySearches: '~2 100',
  },
  {
    id: 'peche',
    keyword: 'journal de bord de pêche',
    title: 'Journal de Pêche',
    subtitle: 'Carnet du pêcheur',
    emoji: '🎣',
    category: 'Loisirs',
    difficulty: 'Facile',
    volumeScore: 58,
    volumeLevel: 'Moyen',
    opportunityScore: 'A',
    trend: 'stable',
    description: 'Marché fidèle et sous-exploité sur KDP. Le pêcheur note ses spots, espèces, conditions — carnet idéal.',
    tags: ['pêche', 'carnet spot', 'poisson', 'fishing log'],
    monthlySearches: '~1 800',
  },
  {
    id: 'grossesse',
    keyword: 'carnet de suivi grossesse',
    title: 'Journal Grossesse',
    subtitle: 'Suivi semaine par semaine',
    emoji: '🤰',
    category: 'Famille',
    difficulty: 'Moyen',
    volumeScore: 82,
    volumeLevel: 'Haut',
    opportunityScore: 'B+',
    trend: 'up',
    description: 'Marché large et émotionnel. Les mamans veulent un journal premium. Gros potentiel de prix élevé (12–18 $).',
    tags: ['grossesse', 'maternité', 'bébé', 'journal'],
    monthlySearches: '~12 000',
  },
  {
    id: 'musculation',
    keyword: 'journal dentraînement musculation',
    title: 'Journal Muscu',
    subtitle: 'Suivi entraînement & nutrition',
    emoji: '💪',
    category: 'Sport & Fitness',
    difficulty: 'Moyen',
    volumeScore: 76,
    volumeLevel: 'Haut',
    opportunityScore: 'B',
    trend: 'up',
    description: 'Recherches en hausse post-COVID. Le public fitness achète facilement. Concurrence présente mais qualité médiocre.',
    tags: ['musculation', 'fitness', 'entraînement', 'nutrition'],
    monthlySearches: '~9 500',
  },
  {
    id: 'jardinage',
    keyword: 'carnet de jardinage potager',
    title: 'Carnet Potager',
    subtitle: 'Planification & récoltes',
    emoji: '🌿',
    category: 'Jardin',
    difficulty: 'Facile',
    volumeScore: 60,
    volumeLevel: 'Moyen',
    opportunityScore: 'A',
    trend: 'hot',
    description: 'Boom du jardinage urbain. Niche peu exploitée, forte conversion. Idéal pour un premier produit KDP.',
    tags: ['potager', 'jardin', 'légumes', 'permaculture'],
    monthlySearches: '~2 900',
  },
  {
    id: 'meditation',
    keyword: 'journal de méditation mindfulness',
    title: 'Journal Méditation',
    subtitle: 'Pleine conscience & gratitude',
    emoji: '🧘',
    category: 'Bien-être',
    difficulty: 'Dur',
    volumeScore: 88,
    volumeLevel: 'Haut',
    opportunityScore: 'C+',
    trend: 'up',
    description: "Marché très porteur mais saturé. Différenciation nécessaire (niche langue, tranche d'âge, méthode spécifique).",
    tags: ['méditation', 'mindfulness', 'bien-être', 'gratitude'],
    monthlySearches: '~22 000',
  },
  {
    id: 'budget',
    keyword: 'carnet de budget mensuel',
    title: 'Carnet Budget',
    subtitle: 'Suivi finances personnelles',
    emoji: '💰',
    category: 'Finance',
    difficulty: 'Moyen',
    volumeScore: 74,
    volumeLevel: 'Haut',
    opportunityScore: 'B+',
    trend: 'hot',
    description: "Explosion des recherches finance perso. Les planners de budget se vendent très bien, surtout en début d'année.",
    tags: ['budget', 'épargne', 'finance', 'dépenses'],
    monthlySearches: '~7 200',
  },
];

export const CATEGORIES = [...new Set(TRENDING_NICHES.map(n => n.category))];
